apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo Hi I am $HOSTNAME; sleep 2;done"]
